name: Main workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubunut-16.04
    name: Run Build
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm test
      - run: npm build
